package_rename_config:
  android:
    app_name: Material Task Tracker # (String) The display name of the android app
    package_name: mtt.architxkumar.dev # (String) The package name of the android app
    override_old_package: # (Optional) (String) Use this to delete the old folder structure of MainActivity or to use the existing code with the new package name
    lang: # (Optional) (String) The android development language {kotlin(default) or java}

  ios:
    app_name: # (String) The display name of the ios app
    bundle_name: # (String) The bundle name of the ios app
    package_name: # (String) The product bundle identifier of the ios app

  linux:
    app_name: # (String) The window title of the linux app
    package_name: # (String) The application id of the linux app
    exe_name: # (String) The executable name (binary name) of the linux app

  macos:
    app_name: # (String) The product name of the macos app
    package_name: # (String) The product bundle identifier of the macos app
    copyright_notice: # (String) The product copyright of the macos app

  web:
    app_name: Material Task Tracker # (String) The title of the web app and PWA
    short_app_name: Material Task Tracker # (String) The short display name of the PWA (Optional, defaults to app_name if not set)
    description: A to do app built with Material Design in Flutter # (String) The description of the web app and PWA

  windows:
      app_name: Material Task Tracker
      organization: architxkumar
      copyright_notice: Copyright Â© 2025 Archit Kumar
      exe_name: material_task_tracker