name: material_task_tracker
description: "A task tracker app built in Flutter"

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5
  result_dart: ^2.1.1
  logger: ^2.6.2
  package_rename: ^1.10.0
  provider: ^6.1.5+1
  format: ^1.6.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.1

flutter:

  uses-material-design: true

